# Generated by Django 5.2.14 on 2026-05-20 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("recording", "Recording"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube Live"),
                            ("local", "Local Recording"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("stream_key", models.CharField(blank=True, max_length=200)),
                ("youtube_broadcast_id", models.CharField(blank=True, max_length=200)),
                ("youtube_stream_url", models.URLField(blank=True)),
                ("recording_path", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_sessions",
                        to="rooms.room",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_streams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "streaming_session",
                "ordering": ["-created_at"],
            },
        ),
    ]
